# Generated by Django 4.0.6 on 2022-12-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_products_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders_details',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='orders_details',
            name='prod_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orders',
            name='district',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orders',
            name='phone_num',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orders',
            name='postal_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orders_details',
            name='desc',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orders_details',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders_details',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders_details',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
