# Generated by Django 4.0.6 on 2022-12-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_orders_details_patch_orders_details_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_details',
            name='back_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
